import { MODULE_CODES, PERMISSIONS } from '../../config/constants';

export const SAMA_ROUTE_PERMISSIONS = [
  PERMISSIONS.SAMA_VIEW_SELF,
  PERMISSIONS.SAMA_VIEW_SOCIETY,
  PERMISSIONS.SAMA_VIEW_STAFF,
  PERMISSIONS.SAMA_CONFIGURE,
  PERMISSIONS.SAMA_SYNC,
] as const;

export const SAMA_MANIFEST = {
  code: MODULE_CODES.SAMA,
  name: 'SAMA',
  description: 'Society staff bridge, attendance sync, and payroll visibility via EdgeFolio',
  version: '1.0.0',
  status: 'ACTIVE',
  icon: 'Users',
  routePrefix: '/sama',
  apiPrefix: '/api/sama',
  requiredPlan: ['STANDARD', 'PREMIUM', 'ENTERPRISE'],
  defaultEnabled: false,
  permissions: [
    PERMISSIONS.SAMA_VIEW_SELF,
    PERMISSIONS.SAMA_VIEW_SOCIETY,
    PERMISSIONS.SAMA_VIEW_STAFF,
    PERMISSIONS.SAMA_CREATE_STAFF,
    PERMISSIONS.SAMA_EDIT_STAFF,
    PERMISSIONS.SAMA_APPROVE_STAFF,
    PERMISSIONS.SAMA_MANAGE_HOUSEHOLD_ASSOCIATIONS,
    PERMISSIONS.SAMA_MANAGE_STAFF_CATEGORIES,
    PERMISSIONS.SAMA_MANAGE_HOUSEHOLD_PAYMENTS,
    PERMISSIONS.SAMA_MANAGE_SERVICE_POOL,
    PERMISSIONS.SAMA_CREATE_WORK_ORDER,
    PERMISSIONS.SAMA_ASSIGN_WORK_ORDER,
    PERMISSIONS.SAMA_COMPLETE_WORK_ORDER,
    PERMISSIONS.SAMA_MANAGE_ACCESS,
    PERMISSIONS.SAMA_MANAGE_CREDENTIALS,
    PERMISSIONS.SAMA_CONFIGURE,
    PERMISSIONS.SAMA_SYNC,
    PERMISSIONS.SAMA_VIEW_REPORTS,
    PERMISSIONS.SAMA_EXPORT_REPORTS,
    PERMISSIONS.SAMA_VIEW_AUDIT,
  ],
  settingsSchema: {
    provider: { type: 'string', default: 'EDGEFOLIO' },
    bridgeMode: { type: 'string', default: 'PULL' },
  },
} as const;
