import { Router } from 'express';
import { authenticate, requireAnyPermission, requirePermission } from '../../common/middleware/auth';
import { PERMISSIONS } from '../../config/constants';
import { billingPlanController } from './billingPlan.controller';
import { chargeHeadController } from './chargeHead.controller';
import { demandController } from './demand.controller';
import { mcrController } from './mcr.controller';
import { mcrDemandAutomationController } from './mcrDemandAutomation.controller';
import { mcrGatewayController } from './mcrGateway.controller';
import { mcrLateFeeController } from './mcrLateFee.controller';
import { MCR_ROUTE_PERMISSIONS } from './mcr.manifest';
import { mcrPaymentController } from './mcrPayment.controller';
import { mcrPublicReceiptController } from './mcrPublicReceipt.controller';
import { mcrReminderController } from './mcrReminder.controller';
import { mcrReportController } from './mcrReport.controller';
import { mcrReceiptController } from './mcrReceipt.controller';
import { mcrSettingsController } from './mcrSettings.controller';

const router: Router = Router();

router.post('/public/gateway/webhook/:provider', mcrGatewayController.webhook.bind(mcrGatewayController));
router.get('/public/receipts/verify', mcrPublicReceiptController.verify.bind(mcrPublicReceiptController));
router.get('/public/receipts/document', mcrPublicReceiptController.document.bind(mcrPublicReceiptController));
router.get('/public/receipts/poster', mcrPublicReceiptController.poster.bind(mcrPublicReceiptController));
router.use(authenticate);
router.get('/context', requireAnyPermission(...MCR_ROUTE_PERMISSIONS), mcrController.getContext.bind(mcrController));
router.get('/settings', requireAnyPermission(...MCR_ROUTE_PERMISSIONS), mcrSettingsController.get.bind(mcrSettingsController));
router.patch('/settings', requirePermission(PERMISSIONS.MCR_CONFIGURE), mcrSettingsController.update.bind(mcrSettingsController));
router.get('/charge-heads', requireAnyPermission(PERMISSIONS.MCR_VIEW_ALL, PERMISSIONS.MCR_CONFIGURE, PERMISSIONS.MCR_GENERATE_DEMAND), chargeHeadController.list.bind(chargeHeadController));
router.post('/charge-heads', requirePermission(PERMISSIONS.MCR_CONFIGURE), chargeHeadController.create.bind(chargeHeadController));
router.patch('/charge-heads/:id', requirePermission(PERMISSIONS.MCR_CONFIGURE), chargeHeadController.update.bind(chargeHeadController));
router.get('/billing-plans', requireAnyPermission(PERMISSIONS.MCR_VIEW_ALL, PERMISSIONS.MCR_CONFIGURE, PERMISSIONS.MCR_GENERATE_DEMAND), billingPlanController.list.bind(billingPlanController));
router.post('/billing-plans', requirePermission(PERMISSIONS.MCR_CONFIGURE), billingPlanController.create.bind(billingPlanController));
router.patch('/billing-plans/:id', requirePermission(PERMISSIONS.MCR_CONFIGURE), billingPlanController.update.bind(billingPlanController));
router.get('/demands', requireAnyPermission(PERMISSIONS.MCR_VIEW_ALL, PERMISSIONS.MCR_GENERATE_DEMAND, PERMISSIONS.MCR_PUBLISH_DEMAND), demandController.list.bind(demandController));
router.post('/demands/drafts', requirePermission(PERMISSIONS.MCR_GENERATE_DEMAND), demandController.createDrafts.bind(demandController));
router.post('/demands/automation/run', requirePermission(PERMISSIONS.MCR_GENERATE_DEMAND), requirePermission(PERMISSIONS.MCR_PUBLISH_DEMAND), mcrDemandAutomationController.run.bind(mcrDemandAutomationController));
router.post('/demands/:demandId/publish', requirePermission(PERMISSIONS.MCR_PUBLISH_DEMAND), demandController.publish.bind(demandController));
router.post('/demands/:demandId/cancel', requirePermission(PERMISSIONS.MCR_PUBLISH_DEMAND), demandController.cancel.bind(demandController));
router.post('/demands/:demandId/reminders', requirePermission(PERMISSIONS.MCR_SEND_REMINDER), mcrReminderController.sendForDemand.bind(mcrReminderController));
router.post('/late-fees/run', requirePermission(PERMISSIONS.MCR_GENERATE_DEMAND), mcrLateFeeController.run.bind(mcrLateFeeController));
router.get('/payments', requireAnyPermission(PERMISSIONS.MCR_VIEW_ALL, PERMISSIONS.MCR_RECORD_PAYMENT, PERMISSIONS.MCR_VERIFY_PAYMENT), mcrPaymentController.list.bind(mcrPaymentController));
router.get('/payments/upi-qr', requireAnyPermission(...MCR_ROUTE_PERMISSIONS), mcrPaymentController.getUpiQr.bind(mcrPaymentController));
router.get('/payments/:paymentId', requireAnyPermission(PERMISSIONS.MCR_VIEW_ALL, PERMISSIONS.MCR_RECORD_PAYMENT, PERMISSIONS.MCR_VERIFY_PAYMENT), mcrPaymentController.getById.bind(mcrPaymentController));
router.post('/payments', requirePermission(PERMISSIONS.MCR_RECORD_PAYMENT), mcrPaymentController.create.bind(mcrPaymentController));
router.post('/payments/self', requirePermission(PERMISSIONS.MCR_SUBMIT_PAYMENT), mcrPaymentController.submitSelf.bind(mcrPaymentController));
router.post('/payments/:paymentId/verify', requirePermission(PERMISSIONS.MCR_VERIFY_PAYMENT), mcrPaymentController.verify.bind(mcrPaymentController));
router.post('/payments/:paymentId/reject', requirePermission(PERMISSIONS.MCR_REJECT_PAYMENT), mcrPaymentController.reject.bind(mcrPaymentController));
router.post('/payments/:paymentId/cancel', requirePermission(PERMISSIONS.MCR_CANCEL_PAYMENT), mcrPaymentController.cancel.bind(mcrPaymentController));
router.post('/payments/:paymentId/bounce', requirePermission(PERMISSIONS.MCR_CANCEL_PAYMENT), mcrPaymentController.bounce.bind(mcrPaymentController));
router.get('/gateway/config', requirePermission(PERMISSIONS.MCR_MANAGE_PAYMENT_GATEWAY), mcrGatewayController.getConfig.bind(mcrGatewayController));
router.patch('/gateway/config', requirePermission(PERMISSIONS.MCR_MANAGE_PAYMENT_GATEWAY), mcrGatewayController.updateConfig.bind(mcrGatewayController));
router.post('/gateway/orders', requireAnyPermission(PERMISSIONS.MCR_MANAGE_PAYMENT_GATEWAY, PERMISSIONS.MCR_RECORD_PAYMENT, PERMISSIONS.MCR_VIEW_SELF), mcrGatewayController.createOrder.bind(mcrGatewayController));
router.get('/receipts', requireAnyPermission(PERMISSIONS.MCR_VIEW_ALL, PERMISSIONS.MCR_GENERATE_RECEIPT, PERMISSIONS.MCR_RECORD_PAYMENT, PERMISSIONS.MCR_VERIFY_PAYMENT), mcrReceiptController.list.bind(mcrReceiptController));
router.get('/payments/:paymentId/receipt', requireAnyPermission(PERMISSIONS.MCR_VIEW_ALL, PERMISSIONS.MCR_GENERATE_RECEIPT, PERMISSIONS.MCR_RECORD_PAYMENT, PERMISSIONS.MCR_VERIFY_PAYMENT), mcrReceiptController.getByPaymentId.bind(mcrReceiptController));
router.get('/receipts/:receiptId', requireAnyPermission(PERMISSIONS.MCR_VIEW_ALL, PERMISSIONS.MCR_GENERATE_RECEIPT, PERMISSIONS.MCR_RECORD_PAYMENT, PERMISSIONS.MCR_VERIFY_PAYMENT), mcrReceiptController.getById.bind(mcrReceiptController));
router.get('/receipts/:receiptId/document', requireAnyPermission(PERMISSIONS.MCR_VIEW_ALL, PERMISSIONS.MCR_GENERATE_RECEIPT, PERMISSIONS.MCR_RECORD_PAYMENT, PERMISSIONS.MCR_VERIFY_PAYMENT), mcrReceiptController.document.bind(mcrReceiptController));
router.get('/receipts/:receiptId/download', requireAnyPermission(PERMISSIONS.MCR_VIEW_ALL, PERMISSIONS.MCR_GENERATE_RECEIPT, PERMISSIONS.MCR_RECORD_PAYMENT, PERMISSIONS.MCR_VERIFY_PAYMENT), mcrReceiptController.download.bind(mcrReceiptController));
router.get('/receipts/:receiptId/poster', requireAnyPermission(PERMISSIONS.MCR_VIEW_ALL, PERMISSIONS.MCR_GENERATE_RECEIPT, PERMISSIONS.MCR_RECORD_PAYMENT, PERMISSIONS.MCR_VERIFY_PAYMENT), mcrReceiptController.poster.bind(mcrReceiptController));
router.get('/receipts/:receiptId/share', requireAnyPermission(PERMISSIONS.MCR_VIEW_ALL, PERMISSIONS.MCR_GENERATE_RECEIPT, PERMISSIONS.MCR_RECORD_PAYMENT, PERMISSIONS.MCR_VERIFY_PAYMENT), mcrReceiptController.share.bind(mcrReceiptController));
router.post('/receipts/:receiptId/void', requirePermission(PERMISSIONS.MCR_VOID_RECEIPT), mcrReceiptController.void.bind(mcrReceiptController));
router.post('/receipts/:receiptId/replace', requirePermission(PERMISSIONS.MCR_VOID_RECEIPT), mcrReceiptController.replace.bind(mcrReceiptController));
router.post('/receipts/:receiptId/send', requirePermission(PERMISSIONS.MCR_GENERATE_RECEIPT), mcrReceiptController.send.bind(mcrReceiptController));
router.post('/reminders/run', requirePermission(PERMISSIONS.MCR_SEND_REMINDER), mcrReminderController.runOutstanding.bind(mcrReminderController));
router.get('/reports/summary', requireAnyPermission(...MCR_ROUTE_PERMISSIONS, PERMISSIONS.MCR_EXPORT_REPORTS), mcrReportController.getSummary.bind(mcrReportController));
router.get('/reports/summary-by-tower', requireAnyPermission(...MCR_ROUTE_PERMISSIONS, PERMISSIONS.MCR_EXPORT_REPORTS), mcrReportController.getSummaryByTower.bind(mcrReportController));
router.get('/reports/statement', requireAnyPermission(...MCR_ROUTE_PERMISSIONS, PERMISSIONS.MCR_EXPORT_REPORTS), mcrReportController.getStatement.bind(mcrReportController));
router.get('/reports/collections', requireAnyPermission(...MCR_ROUTE_PERMISSIONS, PERMISSIONS.MCR_EXPORT_REPORTS), mcrReportController.listCollections.bind(mcrReportController));

export default router;
