import { MCR_MANIFEST } from '../modules/mcr/mcr.manifest';
import { SAMA_MANIFEST } from '../modules/sama/sama.manifest';

export const MODULES_SEED = [
  { code: 'CORE', name: 'Core Platform', description: 'Foundation module for all society management', version: '1.0.0', status: 'ACTIVE', icon: 'Home', routePrefix: '/', apiPrefix: '/api', requiredPlan: ['BASIC','STANDARD','PREMIUM','ENTERPRISE'], defaultEnabled: true, permissions: [] },
  { code: 'PARKING', name: 'Parking & Boom Barrier', description: 'Vehicle parking management with UHF reader integration', version: '1.0.0', status: 'COMING_SOON', icon: 'ParkingCircle', routePrefix: '/parking', apiPrefix: '/api/parking', requiredPlan: ['STANDARD','PREMIUM','ENTERPRISE'], defaultEnabled: false, permissions: [] },
  { code: 'VISITOR', name: 'Visitor Management', description: 'Gate pass, visitor approval and tracking', version: '1.0.0', status: 'ACTIVE', icon: 'UserCheck', routePrefix: '/visitor', apiPrefix: '/api/visitor', requiredPlan: ['STANDARD','PREMIUM','ENTERPRISE'], defaultEnabled: false, permissions: ['visitor.request.create','visitor.request.view_assigned_gate','visitor.request.view_own_flat','visitor.request.respond_own_flat','visitor.entry.confirm','visitor.exit.confirm','visitor.request.cancel','visitor.request.override','visitor.report.view','visitor.settings.manage','visitor.audit.view'] },
  MCR_MANIFEST,
  { code: 'BOOKING', name: 'Facility Booking', description: 'Book common areas like hall, pool, gym etc.', version: '1.0.0', status: 'COMING_SOON', icon: 'CalendarCheck', routePrefix: '/booking', apiPrefix: '/api/booking', requiredPlan: ['PREMIUM','ENTERPRISE'], defaultEnabled: false, permissions: [] },
  { code: 'ACCESS_CONTROL', name: 'Member Access Control', description: 'Gym, spa, pool access management', version: '1.0.0', status: 'COMING_SOON', icon: 'KeyRound', routePrefix: '/access', apiPrefix: '/api/access', requiredPlan: ['PREMIUM','ENTERPRISE'], defaultEnabled: false, permissions: [] },
  { code: 'ANNOUNCEMENT', name: 'Announcements & Events', description: 'Society-wide announcements, events, fundraising', version: '1.0.0', status: 'COMING_SOON', icon: 'Megaphone', routePrefix: '/announcements', apiPrefix: '/api/announcements', requiredPlan: ['BASIC','STANDARD','PREMIUM','ENTERPRISE'], defaultEnabled: false, permissions: [] },
  { code: 'FUND_AUDIT', name: 'Fund & Audit', description: 'Transparent fund utilization and audit reports', version: '1.0.0', status: 'COMING_SOON', icon: 'BarChart3', routePrefix: '/fund-audit', apiPrefix: '/api/fund-audit', requiredPlan: ['STANDARD','PREMIUM','ENTERPRISE'], defaultEnabled: false, permissions: [] },
  { code: 'COMPLAINT', name: 'Complaint Management', description: 'Resident complaint tracking and resolution', version: '1.0.0', status: 'COMING_SOON', icon: 'MessageSquareWarning', routePrefix: '/complaints', apiPrefix: '/api/complaints', requiredPlan: ['BASIC','STANDARD','PREMIUM','ENTERPRISE'], defaultEnabled: false, permissions: [] },
  SAMA_MANIFEST,
  { code: 'DELIVERY', name: 'Delivery Management', description: 'Package and delivery tracking for residents', version: '1.0.0', status: 'COMING_SOON', icon: 'Package', routePrefix: '/delivery', apiPrefix: '/api/delivery', requiredPlan: ['BASIC','STANDARD','PREMIUM','ENTERPRISE'], defaultEnabled: false, permissions: [] },
  { code: 'EMERGENCY', name: 'Emergency & SOS', description: 'Emergency alerts and SOS notifications', version: '1.0.0', status: 'COMING_SOON', icon: 'Siren', routePrefix: '/emergency', apiPrefix: '/api/emergency', requiredPlan: ['STANDARD','PREMIUM','ENTERPRISE'], defaultEnabled: false, permissions: [] },
  { code: 'POLLING', name: 'Polling & Voting', description: 'Society polls and resident voting', version: '1.0.0', status: 'COMING_SOON', icon: 'Vote', routePrefix: '/polling', apiPrefix: '/api/polling', requiredPlan: ['BASIC','STANDARD','PREMIUM','ENTERPRISE'], defaultEnabled: false, permissions: [] },
  { code: 'DOCUMENT', name: 'Document Management', description: 'Society documents and file management', version: '1.0.0', status: 'COMING_SOON', icon: 'FileText', routePrefix: '/documents', apiPrefix: '/api/documents', requiredPlan: ['BASIC','STANDARD','PREMIUM','ENTERPRISE'], defaultEnabled: false, permissions: [] },
  { code: 'ASSET_AMC', name: 'Asset & AMC', description: 'Common area asset tracking and AMC management', version: '1.0.0', status: 'COMING_SOON', icon: 'Wrench', routePrefix: '/assets', apiPrefix: '/api/assets', requiredPlan: ['STANDARD','PREMIUM','ENTERPRISE'], defaultEnabled: false, permissions: [] },
  { code: 'IOT_HEALTH', name: 'IoT Device Health', description: 'Real-time monitoring of all IoT devices', version: '1.0.0', status: 'COMING_SOON', icon: 'Activity', routePrefix: '/iot-health', apiPrefix: '/api/iot-health', requiredPlan: ['PREMIUM','ENTERPRISE'], defaultEnabled: false, permissions: [] },
];
