import { PERMISSIONS } from '../config/constants';

export const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  JENIX_SUPER_ADMIN: ALL_PERMISSIONS,
  JENIX_SUPPORT: [
    PERMISSIONS.SOCIETY_READ, PERMISSIONS.TOWER_READ, PERMISSIONS.FLAT_READ,
    PERMISSIONS.RESIDENT_READ, PERMISSIONS.VEHICLE_READ, PERMISSIONS.PET_READ,
    PERMISSIONS.MODULE_READ, PERMISSIONS.DEVICE_READ, PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.NOTIFICATION_READ, PERMISSIONS.AUDIT_READ, PERMISSIONS.REPORT_READ,
    PERMISSIONS.USER_READ, PERMISSIONS.ROLE_READ,
  ],
  SOCIETY_ADMIN: [
    PERMISSIONS.SOCIETY_READ, PERMISSIONS.SOCIETY_UPDATE,
    PERMISSIONS.TOWER_CREATE, PERMISSIONS.TOWER_READ, PERMISSIONS.TOWER_UPDATE, PERMISSIONS.TOWER_DELETE,
    PERMISSIONS.FLAT_CREATE, PERMISSIONS.FLAT_READ, PERMISSIONS.FLAT_UPDATE, PERMISSIONS.FLAT_DELETE,
    PERMISSIONS.RESIDENT_CREATE, PERMISSIONS.RESIDENT_READ, PERMISSIONS.RESIDENT_UPDATE, PERMISSIONS.RESIDENT_DISABLE,
    PERMISSIONS.VEHICLE_CREATE, PERMISSIONS.VEHICLE_READ, PERMISSIONS.VEHICLE_UPDATE, PERMISSIONS.VEHICLE_DISABLE,
    PERMISSIONS.PET_CREATE, PERMISSIONS.PET_READ, PERMISSIONS.PET_UPDATE, PERMISSIONS.PET_DISABLE,
    PERMISSIONS.MODULE_ENABLE, PERMISSIONS.MODULE_DISABLE, PERMISSIONS.MODULE_READ,
    PERMISSIONS.DEVICE_CREATE, PERMISSIONS.DEVICE_READ, PERMISSIONS.DEVICE_UPDATE, PERMISSIONS.DEVICE_DISABLE,
    PERMISSIONS.PAYMENT_CREATE, PERMISSIONS.PAYMENT_READ, PERMISSIONS.RECEIPT_GENERATE,
    PERMISSIONS.NOTIFICATION_READ, PERMISSIONS.AUDIT_READ, PERMISSIONS.REPORT_READ, PERMISSIONS.FILE_UPLOAD,
    PERMISSIONS.USER_CREATE, PERMISSIONS.USER_READ, PERMISSIONS.USER_UPDATE, PERMISSIONS.ROLE_READ,
  ],
  COMMITTEE_MEMBER: [
    PERMISSIONS.SOCIETY_READ, PERMISSIONS.TOWER_READ, PERMISSIONS.FLAT_READ,
    PERMISSIONS.RESIDENT_READ, PERMISSIONS.VEHICLE_READ, PERMISSIONS.PET_READ,
    PERMISSIONS.PAYMENT_READ, PERMISSIONS.REPORT_READ, PERMISSIONS.AUDIT_READ,
    PERMISSIONS.NOTIFICATION_READ, PERMISSIONS.MODULE_READ,
  ],
  ACCOUNTANT: [
    PERMISSIONS.SOCIETY_READ, PERMISSIONS.FLAT_READ, PERMISSIONS.RESIDENT_READ,
    PERMISSIONS.PAYMENT_CREATE, PERMISSIONS.PAYMENT_READ, PERMISSIONS.RECEIPT_GENERATE,
    PERMISSIONS.REPORT_READ, PERMISSIONS.NOTIFICATION_READ, PERMISSIONS.FILE_UPLOAD,
  ],
  SECURITY_GUARD: [
    PERMISSIONS.RESIDENT_READ, PERMISSIONS.VEHICLE_READ, PERMISSIONS.DEVICE_READ,
    PERMISSIONS.NOTIFICATION_READ,
  ],
  FACILITY_MANAGER: [
    PERMISSIONS.SOCIETY_READ, PERMISSIONS.FLAT_READ, PERMISSIONS.RESIDENT_READ,
    PERMISSIONS.DEVICE_READ, PERMISSIONS.MODULE_READ, PERMISSIONS.NOTIFICATION_READ,
  ],
  OWNER: [
    PERMISSIONS.RESIDENT_READ, PERMISSIONS.VEHICLE_READ, PERMISSIONS.PET_READ,
    PERMISSIONS.PAYMENT_READ, PERMISSIONS.NOTIFICATION_READ,
  ],
  TENANT: [PERMISSIONS.RESIDENT_READ, PERMISSIONS.NOTIFICATION_READ],
  FAMILY_MEMBER: [PERMISSIONS.NOTIFICATION_READ],
  VENDOR: [PERMISSIONS.NOTIFICATION_READ],
  STAFF: [PERMISSIONS.NOTIFICATION_READ],
};
