export const ROLES = {
  JENIX_SUPER_ADMIN: 'JENIX_SUPER_ADMIN',
  JENIX_SUPPORT: 'JENIX_SUPPORT',
  SOCIETY_ADMIN: 'SOCIETY_ADMIN',
  COMMITTEE_MEMBER: 'COMMITTEE_MEMBER',
  ACCOUNTANT: 'ACCOUNTANT',
  SECURITY_GUARD: 'SECURITY_GUARD',
  FACILITY_MANAGER: 'FACILITY_MANAGER',
  OWNER: 'OWNER',
  TENANT: 'TENANT',
  FAMILY_MEMBER: 'FAMILY_MEMBER',
  VENDOR: 'VENDOR',
  STAFF: 'STAFF',
} as const;

export const PERMISSIONS = {
  SOCIETY_CREATE: 'society.create',
  SOCIETY_READ: 'society.read',
  SOCIETY_UPDATE: 'society.update',
  SOCIETY_DISABLE: 'society.disable',
  TOWER_CREATE: 'tower.create',
  TOWER_READ: 'tower.read',
  TOWER_UPDATE: 'tower.update',
  TOWER_DELETE: 'tower.delete',
  FLAT_CREATE: 'flat.create',
  FLAT_READ: 'flat.read',
  FLAT_UPDATE: 'flat.update',
  FLAT_DELETE: 'flat.delete',
  RESIDENT_CREATE: 'resident.create',
  RESIDENT_READ: 'resident.read',
  RESIDENT_UPDATE: 'resident.update',
  RESIDENT_DISABLE: 'resident.disable',
  VEHICLE_CREATE: 'vehicle.create',
  VEHICLE_READ: 'vehicle.read',
  VEHICLE_UPDATE: 'vehicle.update',
  VEHICLE_DISABLE: 'vehicle.disable',
  PET_CREATE: 'pet.create',
  PET_READ: 'pet.read',
  PET_UPDATE: 'pet.update',
  PET_DISABLE: 'pet.disable',
  MODULE_ENABLE: 'module.enable',
  MODULE_DISABLE: 'module.disable',
  MODULE_READ: 'module.read',
  DEVICE_CREATE: 'device.create',
  DEVICE_READ: 'device.read',
  DEVICE_UPDATE: 'device.update',
  DEVICE_DISABLE: 'device.disable',
  PAYMENT_CREATE: 'payment.create',
  PAYMENT_READ: 'payment.read',
  RECEIPT_GENERATE: 'receipt.generate',
  NOTIFICATION_READ: 'notification.read',
  AUDIT_READ: 'audit.read',
  REPORT_READ: 'report.read',
  FILE_UPLOAD: 'file.upload',
  USER_CREATE: 'user.create',
  USER_READ: 'user.read',
  USER_UPDATE: 'user.update',
  ROLE_CREATE: 'role.create',
  ROLE_READ: 'role.read',
  ROLE_UPDATE: 'role.update',
} as const;

export const MODULE_CODES = {
  CORE: 'CORE',
  PARKING: 'PARKING',
  VISITOR: 'VISITOR',
  MAINTENANCE: 'MAINTENANCE',
  BOOKING: 'BOOKING',
  ACCESS_CONTROL: 'ACCESS_CONTROL',
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  FUND_AUDIT: 'FUND_AUDIT',
  COMPLAINT: 'COMPLAINT',
  STAFF: 'STAFF',
  DELIVERY: 'DELIVERY',
  EMERGENCY: 'EMERGENCY',
  POLLING: 'POLLING',
  DOCUMENT: 'DOCUMENT',
  ASSET_AMC: 'ASSET_AMC',
  IOT_HEALTH: 'IOT_HEALTH',
} as const;

export const DEFAULT_PAGINATION = { page: 1, limit: 20 };
export const BCRYPT_ROUNDS = 12;
export const SOCIETY_CODE_PREFIX = 'JSO';
